apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - env:
            - name: WEB_HOST
              valueFrom:
                configMapKeyRef:
                  name: frontend
                  key: WEB_HOST
            - name: WEB_PORT
              valueFrom:
                configMapKeyRef:
                  name: frontend
                  key: WEB_PORT
          name: frontend
          # image: "docker.local:5000/my_booker_ui:latest"
          # image: "mybookerweb.int.repositories.cloud.sap/mybookerui:latest"
          image: "mayankraipure/mybookerui:0.0.5"
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regdockercred
