apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentVersion
metadata:
  name: booker
  namespace: ocm-system
spec:
  interval: 10m0s
  component: booker.io/book
  version:
    semver: v1.0.5
  repository:
    url: ghcr.io/mayankraipure12
    secretRef:
      name: creds
  verify:
    - name: alice
      publicKey:
        secretRef:
          name: alice-publickey
